---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install at {{ kopia_install_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ kopia_install_exe }}'
  register: kopia_binary
- name: Downloading and installing kopia
  when: not kopia_binary.stat.exists
  block:
    - name: Downloading {{ kopia_url }} to {{ kopia_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ kopia_url }}'
        dest: '{{ kopia_tmp_archive }}'
        checksum: '{{ kopia_checksum }}'
        mode: '644'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchive {{ kopia_tmp_archive }} to {{ kopia_parent_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ kopia_tmp_archive }}'
        dest: '{{ kopia_parent_install_dir }}'
        creates: '{{ kopia_install_dir }}'
  always:
    - name: Rm -rf {{ kopia_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ kopia_tmp_archive }}'
        state: absent
- name: Linking {{ kopia_link }} to {{ kopia_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ kopia_install_exe }}'
    dest: '{{ kopia_link }}'
    state: link
